### PR TITLE
Add travis-ci build script

### PR DESCRIPTION
**Pull request by honzabrecka**
Continuous builds using Travis-CI service:
https://travis-ci.org/honzabrecka/feathers/builds/55518151

I think this would be useful to validate other feature requests too, using automated scripts.

Cheers!

### CODE REVIEW

**Comment by honzabrecka** [comment]
Unit tests are failing - I'm not sure if master is broken or not?

**Comment by joshtynjala** [comment]
Strange. I just ran the tests on master, and they all passed on my machine.

**Comment by honzabrecka** [comment]
Tests are failing due to the latest Starling changes. The problem is that Feathers build depends on the latest Starling revision from master, which may contain BC incompatible changes, which will lead to many false positive failures. Shouldn't be Starling added as a submodule? Then it can be locked on compatible revision.

I'm new to Feathers, so perhaps I'm missing something. :)

**Comment by joshtynjala** [comment]
I don't think a submodule would make sense. Starling isn't being distributed with Feathers, so it shouldn't be in the repo. Instead, I think the .travis.yml file should be updated whenever I change the minimum required version of Starling. It can check out a specific tag, most of the time. Up until recently, that would have been the v1.6 tag.

We're currently in an uncommon situation where Feathers requires a feature in Starling that hasn't been released yet. Most of the time, I try to avoid that, but the upcoming VideoPlayer component needs VideoTexture support.

I haven't updated my local copy of Starling in a couple of weeks, so it may be possible that the most recent commits have changed something that breaks the unit tests. I'll investigate when I get a chance.

**Comment by honzabrecka** [comment]
@PrimaryFeather just fixed the issue, so all tests passed. I think it's ready for merge.

**Comment by honzabrecka** [comment]
To take effect and check every commit/PR it's necessary to setup travis-ci. If you aren't familiar with travis-ci, here's how to do it: http://docs.travis-ci.com/user/getting-started/#Step-one%3A-Sign-in and http://docs.travis-ci.com/user/getting-started/#Step-two%3A-Activate-GitHub-Webhook

**Comment by PrimaryFeather** [comment]
Sorry about the troubles with yesterday's [commit](https://github.com/Gamua/Starling-Framework/commit/5232a925ad78facb8fcea768c387e8138ea0b5c6)!

What I did was add support for negative child indices when accessing them, so you're e.g. able to use

```as3
var child:DisplayObject = container.getChildAt(-1);
```

to access the last child of a container. I didn't anticipate problems, but forget that anyone overriding "addChildAt" would have to support that, too.

I'm considering to limit that change to "getChildAt", and revert the changes of "addChildAt" and "removeChildAt", though, if that's preferred.

**Comment by joshtynjala** [comment]
@honzabrecka Every once in a while, an error happens in the Travis CI build when trying to install the software. Here's the relevant part of the log when it happened today:

	$ brew install ant adobe-air-sdk pandoc > /dev/null
	Error: SHA1 mismatch
	Expected: 4f081a579cf0f15d13118a08ab5a502aa4c0d848
	Actual: dc4f412fe7d11849f62a6b8aa55b39ea1bc96c91
	Archive: /Library/Caches/Homebrew/adobe-air-sdk-17.0.0.124.tbz2
	To retry an incomplete download, remove the file above.

	The command "brew install ant adobe-air-sdk pandoc > /dev/null" failed and exited with 1 during .

	Your build has been stopped.

https://travis-ci.org/joshtynjala/feathers/builds/59815875

**Comment by honzabrecka** [comment]
@joshtynjala Sorry for the delay. I prepared a PR that should fix the issue.

**Pull request merged**
