### PR TITLE
HorizontalLayout, VerticalLayout: wrong item positioning was fixed.

### PR DESCRIPTION
**Pull request by kavolorn**
Hi Josh,
I've fixed wrong item positioning for Vertical and Horizontal layouts. It was there since first version of Feathers.

### CODE REVIEW

**Comment by zenrobin** [comment]
Perhaps this is why I'm often scratching my head when a list positions in
an unexpected place. I've had to put in many (ugly) workarounds just to
make sure my lists get positioned correctly.

Looking forward to trying this out!

**Comment by joshtynjala** [comment]
You removed the call to Math.round() which was there for a reason. If you put that back, and then move the comment about it to the right place, I'll merge it.

**Comment by joshtynjala** [comment]
@zenrobin Can you submit bug reports for that sort of thing in the future? I can't fix things that I don't know about!

**Comment by kavolorn** [comment]
It seems second commit is in the request. Sorry, I missed round operation.

**Pull request merged**
